### ISSUE TITLE
Prevents tab completion of commands

### ISSUE THREAD

**Issue by LucilleTea** [Sturmlilie/duyguji-client-base#1]
When Duyguji is installed, minecraft commands (eg. /gamemode) cannot be tab completed. Issue present in singleplayer with no other mods, Minecraft 1.16.1, Duyguji 0.2.1.

**Comment by Sturmlilie** [comment]
Thank you, and yikes that's embarrassing. Are you comfortable building from source, or would you like me to make a patch release?

**Comment by LucilleTea** [comment]
I'm happy to build it for myself, but I suspect other users would like to use the fixed version too.

**Comment by Sturmlilie** [comment]
You're right
