### ISSUE TITLE
Server emote idea

### ISSUE THREAD

**Issue by Madis0** [Sturmlilie/duyguji-client-base#5]
> Please note that this is a very early development version, support is planned for all popular messenger emotes (like the ones at the top) as well as per-server custom emotes.

You might want to check out this resource pack, perhaps implement it similarly: https://www.reddit.com/r/Minecraft/comments/1ivbhn/i_made_a_resource_pack_that_adds_over_2000_icons/

**Comment by Sturmlilie** [comment]
Don't worry, I have the architecture mostly planned out, and it will not involve overwriting any Japanese / Chinese UCS-2 characters ;)
